drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 email varchar(255),
 password varchar(255),
 primary key (id)
);

drop table if exists product CASCADE;
create table product
(
 id bigint generated by default as identity,
 name varchar(255),
 qty bigint,
 primary key (id)
);

drop table if exists cart CASCADE;
create table cart
(
memberid bigint,
productid bigint,
cartqty int default 1,
primary key(memberid, productid)
)
--
--select memberid, productid, cartqty
--from member
--join cart
--on member.id = cart.memberid


